movie_db = [
    {"Title": "The Host", "Year": "2006", "Rated": "R", "Released": "30 Mar 2007", "Runtime": "120 min", "Genre": "Action, Drama, Horror, Sci-Fi", "Director": "Bong Joon Ho", "Writer": "Bong Joon Ho (screenplay), Won-jun Ha (screenplay), Chul-hyun Baek (screenplay)", "Actors": "Kang-ho Song, Byun Hee-Bong, Park Hae-il, Bae Doona", "Plot": "A monster emerges from Seoul's Han River and begins attacking people. One victim's loving family does what it can to rescue her from its clutches.", "Language": "Korean, English", "Country": "South Korea", "Awards": "29 wins & 35 nominations.", "Poster": "https://m.media-amazon.com/images/M/MV5BMTE3N2IwNmMtOGE0Ny00NWFlLTliNmUtNjY3ODExYjgxNmUyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg", "Ratings": [
        {"Source": "Internet Movie Database", "Value": "7.1/10"}, {"Source": "Rotten Tomatoes", "Value": "93%"}, {"Source": "Metacritic", "Value": "85/100"}], "Metascore": "85", "imdbRating": "7.1", "imdbVotes": "110,111", "imdbID": "tt0468492", "Type": "movie", "DVD": "01 Nov 2016", "BoxOffice": "$2,201,923", "Production": "Chockstone Pictures, Silver Reel, Nick Wechsler", "Website": "N/A", "Response": "True"},
    {"Title": "Godzilla vs. Kong", "Year": "2021", "Rated": "PG-13", "Released": "31 Mar 2021", "Runtime": "113 min", "Genre": "Action, Sci-Fi, Thriller", "Director": "Adam Wingard", "Writer": "Terry Rossio (story by), Michael Dougherty (story by), Zach Shields (story by), Eric Pearson (screenplay by), Max Borenstein (screenplay by)", "Actors": "Alexander Skarsgård, Millie Bobby Brown, Rebecca Hall, Brian Tyree Henry", "Plot": "The epic next chapter in the cinematic Monsterverse pits two of the greatest icons in motion picture history against one another - the fearsome Godzilla and the mighty Kong - with humanity caught in the balance.",
     "Language": "English, American Sign Language", "Country": "USA, Australia, Canada, India", "Awards": "N/A", "Poster": "https://m.media-amazon.com/images/M/MV5BZmYzMzU4NjctNDI0Mi00MGExLWI3ZDQtYzQzYThmYzc2ZmNjXkEyXkFqcGdeQXVyMTEyMjM2NDc2._V1_SX300.jpg", "Ratings": [{"Source": "Internet Movie Database", "Value": "6.5/10"}, {"Source": "Rotten Tomatoes", "Value": "75%"}, {"Source": "Metacritic", "Value": "59/100"}], "Metascore": "59", "imdbRating": "6.5", "imdbVotes": "127,056", "imdbID": "tt5034838", "Type": "movie", "DVD": "31 Mar 2021", "BoxOffice": "$95,475,216", "Production": "Warner Bros., Legendary Entertainment", "Website": "N/A", "Response": "True"},
    {"Title": "Alien", "Year": "1979", "Rated": "R", "Released": "22 Jun 1979", "Runtime": "117 min", "Genre": "Horror, Sci-Fi", "Director": "Ridley Scott", "Writer": "Dan O'Bannon (screenplay by), Dan O'Bannon (story by), Ronald Shusett (story by)", "Actors": "Tom Skerritt, Sigourney Weaver, Veronica Cartwright, Harry Dean Stanton", "Plot": "After a space merchant vessel receives an unknown transmission as a distress call, one of the crew is attacked by a mysterious life form and they soon realize that its life cycle has merely begun.", "Language": "English", "Country": "UK, USA", "Awards": "Won 1 Oscar. Another 17 wins & 22 nominations.",
     "Poster": "https://m.media-amazon.com/images/M/MV5BMmQ2MmU3NzktZjAxOC00ZDZhLTk4YzEtMDMyMzcxY2IwMDAyXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg", "Ratings": [{"Source": "Internet Movie Database", "Value": "8.4/10"}, {"Source": "Rotten Tomatoes", "Value": "98%"}, {"Source": "Metacritic", "Value": "89/100"}], "Metascore": "89", "imdbRating": "8.4", "imdbVotes": "803,118", "imdbID": "tt0078748", "Type": "movie", "DVD": "25 Nov 2015", "BoxOffice": "$81,900,459", "Production": "Twentieth Century Fox, Brandywine Productions", "Website": "N/A", "Response": "True"},
    {"Title": "Gremlins", "Year": "1984", "Rated": "PG", "Released": "08 Jun 1984", "Runtime": "106 min", "Genre": "Comedy, Fantasy, Horror", "Director": "Joe Dante", "Writer": "Chris Columbus", "Actors": "Hoyt Axton, John Louie, Keye Luke, Don Steele", "Plot": "A young man inadvertently breaks three important rules concerning his new pet and unleashes a horde of malevolently mischievous monsters on a small town.", "Language": "English, Spanish", "Country": "USA", "Awards": "8 wins & 6 nominations.",
     "Poster": "https://m.media-amazon.com/images/M/MV5BZDVjN2FkYTQtNTBlOC00MjM5LTgzMWEtZWRlNGUyYmNiOTFiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg", "Ratings": [{"Source": "Internet Movie Database", "Value": "7.3/10"}, {"Source": "Rotten Tomatoes", "Value": "85%"}, {"Source": "Metacritic", "Value": "70/100"}], "Metascore": "70", "imdbRating": "7.3", "imdbVotes": "202,705", "imdbID": "tt0087363", "Type": "movie", "DVD": "02 Jun 2014", "BoxOffice": "$153,378,102", "Production": "Warner Brothers, Amblin Entertainment", "Website": "N/A", "Response": "True"},
    {"Title": "Jaws", "Year": "1975", "Rated": "PG", "Released": "20 Jun 1975", "Runtime": "124 min", "Genre": "Adventure, Thriller", "Director": "Steven Spielberg", "Writer": "Peter Benchley (screenplay), Carl Gottlieb (screenplay), Peter Benchley (based on the novel by)", "Actors": "Roy Scheider, Robert Shaw, Richard Dreyfuss, Lorraine Gary", "Plot": "When a killer shark unleashes chaos on a beach community, it's up to a local sheriff, a marine biologist, and an old seafarer to hunt the beast down.", "Language": "English", "Country": "USA", "Awards": "Won 3 Oscars. Another 13 wins & 20 nominations.", "Poster": "https://m.media-amazon.com/images/M/MV5BMmVmODY1MzEtYTMwZC00MzNhLWFkNDMtZjAwM2EwODUxZTA5XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg", "Ratings": [
        {"Source": "Internet Movie Database", "Value": "8.0/10"}, {"Source": "Rotten Tomatoes", "Value": "98%"}, {"Source": "Metacritic", "Value": "87/100"}], "Metascore": "87", "imdbRating": "8.0", "imdbVotes": "549,605", "imdbID": "tt0073195", "Type": "movie", "DVD": "22 Jul 2015", "BoxOffice": "$260,758,300", "Production": "Universal Pictures, Zanuck/Brown Productions", "Website": "N/A", "Response": "True"},
    {"Title": "Megalodon", "Year": "2018", "Rated": "TV-14", "Released": "13 Aug 2018", "Runtime": "88 min", "Genre": "Action, Adventure, Horror, Sci-Fi, Thriller", "Director": "James Thomas", "Writer": "Koichi Petetsky, Thunder Levin (story by), Canyon Prince, James Thomas", "Actors": "Michael Madsen, Caroline Harris, Ego Mikitas, Aimee Stolte", "Plot": "A military vessel on the search for an unidentified submersible finds themselves face to face with a giant shark, forced to use only what they have on board to defend themselves from the monstrous beast.",
     "Language": "English, Russian", "Country": "USA", "Awards": "N/A", "Poster": "https://m.media-amazon.com/images/M/MV5BNjBlNDUzMzAtMTdkNC00NzZiLWFmYjMtMzYyYjZjZjljY2VmXkEyXkFqcGdeQXVyNDcyOTc1OTk@._V1_SX300.jpg", "Ratings": [{"Source": "Internet Movie Database", "Value": "2.9/10"}, {"Source": "Rotten Tomatoes", "Value": "26%"}], "Metascore": "N/A", "imdbRating": "2.9", "imdbVotes": "1,839", "imdbID": "tt8235660", "Type": "movie", "DVD": "26 Oct 2018", "BoxOffice": "N/A", "Production": "The Asylum", "Website": "N/A", "Response": "True"},
    {"Title": "Anaconda", "Year": "1997", "Rated": "PG-13", "Released": "11 Apr 1997", "Runtime": "89 min", "Genre": "Action, Adventure, Horror, Thriller", "Director": "Luis Llosa", "Writer": "Hans Bauer, Jim Cash, Jack Epps Jr.", "Actors": "Jennifer Lopez, Ice Cube, Jon Voight, Eric Stoltz", "Plot": "A \"National Geographic\" film crew is taken hostage by an insane hunter, who forces them along on his quest to capture the world's largest - and deadliest - snake.", "Language": "English", "Country": "USA", "Awards": "6 wins & 11 nominations.",
     "Poster": "https://m.media-amazon.com/images/M/MV5BZDc4ODcyNWMtMzI2Zi00YzcwLWE4ZTUtYWM3OWI1MTgwYTc1XkEyXkFqcGdeQXVyNzc5MjA3OA@@._V1_SX300.jpg", "Ratings": [{"Source": "Internet Movie Database", "Value": "4.8/10"}, {"Source": "Rotten Tomatoes", "Value": "37%"}, {"Source": "Metacritic", "Value": "37/100"}], "Metascore": "37", "imdbRating": "4.8", "imdbVotes": "98,294", "imdbID": "tt0118615", "Type": "movie", "DVD": "16 Apr 2012", "BoxOffice": "$65,885,767", "Production": "Columbia Pictures Corporation", "Website": "N/A", "Response": "True"},
    {"Title": "Troll 2", "Year": "1990", "Rated": "PG-13", "Released": "12 Oct 1990", "Runtime": "95 min", "Genre": "Comedy, Fantasy, Horror", "Director": "Claudio Fragasso", "Writer": "Rossella Drudi (screenplay), Claudio Fragasso (screenplay), Claudio Fragasso (story)", "Actors": "Michael Paul Stephenson, George Hardy, Margo Prey, Connie Young", "Plot": "A vacationing family discovers that the entire town they're visiting is inhabited by goblins, disguised as humans, who plan to eat them.", "Language": "English",
     "Country": "Italy", "Awards": "N/A", "Poster": "https://m.media-amazon.com/images/M/MV5BZmQ4MzZlZTAtNDRhMC00MTQ2LTkyN2YtNTQ1ZTliM2UwMWNhXkEyXkFqcGdeQXVyMTQ2MjQyNDc@._V1_SX300.jpg", "Ratings": [{"Source": "Internet Movie Database", "Value": "3.0/10"}, {"Source": "Rotten Tomatoes", "Value": "5%"}], "Metascore": "N/A", "imdbRating": "3.0", "imdbVotes": "31,073", "imdbID": "tt0105643", "Type": "movie", "DVD": "05 Dec 2016", "BoxOffice": "N/A", "Production": "Filmirage", "Website": "N/A", "Response": "True"},
    {"Title": "Sand Sharks", "Year": "2012", "Rated": "R", "Released": "31 Jul 2012", "Runtime": "86 min", "Genre": "Action, Adventure, Comedy, Horror, Sci-Fi, Thriller", "Director": "Mark Atkins", "Writer": "Joe Benkis (story), Cameron Larson (screenplay), Cameron Larson (story)", "Actors": "Corin Nemec, Brooke Hogan, Vanessa Evigan, Eric Scott Woods", "Plot": "The residents of a small town team up to kill a group of evolved sharks that can swim in sand, and are terrorizing local beaches.", "Language": "English", "Country": "USA", "Awards": "N/A", "Poster": "https://m.media-amazon.com/images/M/MV5BMzg5NjgwNTE0Nl5BMl5BanBnXkFtZTcwNTQ0NzAzOA@@._V1_SX300.jpg", "Ratings": [
        {"Source": "Internet Movie Database", "Value": "2.6/10"}, {"Source": "Rotten Tomatoes", "Value": "13%"}], "Metascore": "N/A", "imdbRating": "2.6", "imdbVotes": "4,808", "imdbID": "tt1844770", "Type": "movie", "DVD": "13 Feb 2017", "BoxOffice": "N/A", "Production": "Little Dragon Productions", "Website": "N/A", "Response": "True"},
    {"Title": "Freddy vs. Jason", "Year": "2003", "Rated": "R", "Released": "15 Aug 2003", "Runtime": "97 min", "Genre": "Action, Horror", "Director": "Ronny Yu", "Writer": "Wes Craven (characters), Victor Miller (characters), Damian Shannon, Mark Swift", "Actors": "Robert Englund, Ken Kirzinger, Monica Keena, Jason Ritter", "Plot": "Freddy Krueger and Jason Voorhees return to terrorize the teenagers of Elm Street. Only this time, they're out to get each other, too.", "Language": "English", "Country": "Canada, USA", "Awards": "2 wins & 11 nominations.", "Poster": "https://m.media-amazon.com/images/M/MV5BODNlNWVjOTMtZjVjYy00MzRjLTg2MmQtNTM3MWVmZjFjYzgwXkEyXkFqcGdeQXVyMzM4MjM0Nzg@._V1_SX300.jpg", "Ratings": [
        {"Source": "Internet Movie Database", "Value": "5.7/10"}, {"Source": "Rotten Tomatoes", "Value": "41%"}, {"Source": "Metacritic", "Value": "37/100"}], "Metascore": "37", "imdbRating": "5.7", "imdbVotes": "111,960", "imdbID": "tt0329101", "Type": "movie", "DVD": "01 Dec 2012", "BoxOffice": "$82,622,655", "Production": "WTC Productions, New Line Cinema, Sean S. Cunningham Films, Avery Pix, Yannix Technology Corp.", "Website": "N/A", "Response": "True"},
    {"Title": "Dragon Wars: D-War", "Year": "2007", "Rated": "PG-13", "Released": "14 Sep 2007", "Runtime": "107 min", "Genre": "Action, Drama, Fantasy, Horror, Thriller", "Director": "Hyung-rae Shim", "Writer": "Hyung-rae Shim", "Actors": "Jason Behr, Amanda Brooks, Robert Forster, Craig Robinson", "Plot": "Once in 500 years, ancient mythical creatures come to Earth, wreaking havoc and destruction. This time they must be stopped.", "Language": "English, Korean", "Country": "South Korea", "Awards": "2 wins & 3 nominations.",
     "Poster": "https://m.media-amazon.com/images/M/MV5BMTc2OTk1MzUzMl5BMl5BanBnXkFtZTcwNjE0ODI1MQ@@._V1_SX300.jpg", "Ratings": [{"Source": "Internet Movie Database", "Value": "3.5/10"}, {"Source": "Rotten Tomatoes", "Value": "30%"}, {"Source": "Metacritic", "Value": "33/100"}], "Metascore": "33", "imdbRating": "3.5", "imdbVotes": "23,792", "imdbID": "tt0372873", "Type": "movie", "DVD": "16 Apr 2012", "BoxOffice": "$10,977,721", "Production": "Showbox Entertainment, Younggu-Art Movies", "Website": "N/A", "Response": "True"},
    {"Title": "Sector 7", "Year": "2011", "Rated": "Not Rated", "Released": "04 Aug 2011", "Runtime": "101 min", "Genre": "Action, Sci-Fi", "Director": "Ji-hoon Kim", "Writer": "JK Youn", "Actors": "Ha Ji-Won, Sung-Ki Ahn, Ji-Ho Oh, Ye-ryeon Cha", "Plot": "A crew, drilling offshore for oil south of Jeju island, finds a lethal alien life form instead.", "Language": "Korean", "Country": "South Korea", "Awards": "N/A",
     "Poster": "https://m.media-amazon.com/images/M/MV5BMTU0MzA0NTc4Nl5BMl5BanBnXkFtZTgwNTQ1MTAzMjE@._V1_SX300.jpg", "Ratings": [{"Source": "Internet Movie Database", "Value": "4.7/10"}, {"Source": "Rotten Tomatoes", "Value": "19%"}], "Metascore": "N/A", "imdbRating": "4.7", "imdbVotes": "2,302", "imdbID": "tt1934381", "Type": "movie", "DVD": "22 Mar 2016", "BoxOffice": "N/A", "Production": "CJ Entertainment", "Website": "N/A", "Response": "True"},
    {"Title": "Venom", "Year": "2018", "Rated": "PG-13", "Released": "05 Oct 2018", "Runtime": "112 min", "Genre": "Action, Adventure, Sci-Fi", "Director": "Ruben Fleischer", "Writer": "Jeff Pinkner (screenplay by), Scott Rosenberg (screenplay by), Kelly Marcel (screenplay by), Jeff Pinkner (screen story by), Scott Rosenberg (screen story by), Todd McFarlane (Marvel's Venom Character created by), David Michelinie (Marvel's Venom Character created by)", "Actors": "Tom Hardy, Michelle Williams, Riz Ahmed, Scott Haze", "Plot": "A failed reporter is bonded to an alien entity, one of many symbiotes who have invaded Earth. But the being takes a liking to Earth and decides to protect it.",
     "Language": "English, Mandarin, Malay", "Country": "China, USA", "Awards": "3 wins & 9 nominations.", "Poster": "https://m.media-amazon.com/images/M/MV5BNzAwNzUzNjY4MV5BMl5BanBnXkFtZTgwMTQ5MzM0NjM@._V1_SX300.jpg", "Ratings": [{"Source": "Internet Movie Database", "Value": "6.7/10"}, {"Source": "Rotten Tomatoes", "Value": "29%"}, {"Source": "Metacritic", "Value": "35/100"}], "Metascore": "35", "imdbRating": "6.7", "imdbVotes": "375,503", "imdbID": "tt1270797", "Type": "movie", "DVD": "18 Jun 2019", "BoxOffice": "$213,515,506", "Production": "Pascal Pictures, Columbia Pictures, Tencent Pictures, Marvel Entertainment", "Website": "N/A", "Response": "True"},
    {"Title": "Okja", "Year": "2017", "Rated": "TV-MA", "Released": "28 Jun 2017", "Runtime": "120 min", "Genre": "Action, Adventure, Drama, Sci-Fi", "Director": "Bong Joon Ho", "Writer": "Bong Joon Ho (screenplay by), Jon Ronson (screenplay by), Bong Joon Ho (story by)", "Actors": "Tilda Swinton, Sheena Kamal, Michael Mitton, Colm Hill", "Plot": "A young girl risks everything to prevent a powerful, multinational company from kidnapping her best friend - a fascinating beast named Okja.", "Language": "English, Korean, Spanish", "Country": "South Korea, USA", "Awards": "7 wins & 21 nominations.", "Poster": "https://m.media-amazon.com/images/M/MV5BMjQxMTcxNDgxN15BMl5BanBnXkFtZTgwOTczNTIzMjI@._V1_SX300.jpg", "Ratings": [
        {"Source": "Internet Movie Database", "Value": "7.3/10"}, {"Source": "Rotten Tomatoes", "Value": "87%"}, {"Source": "Metacritic", "Value": "75/100"}], "Metascore": "75", "imdbRating": "7.3", "imdbVotes": "108,114", "imdbID": "tt3967856", "Type": "movie", "DVD": "30 Jun 2017", "BoxOffice": "N/A", "Production": "Kate Street Picture Company, Plan B Entertainment, Lewis Pictures, Netflix", "Website": "N/A", "Response": "True"},
    {"Title": "Critters Attack!", "Year": "2019", "Rated": "R", "Released": "06 Nov 2020", "Runtime": "89 min", "Genre": "Comedy, Horror, Sci-Fi", "Director": "Bobby Miller", "Writer": "Scott Lobdell", "Actors": "Tashiana Washington, Ava Preston, Jack Fulton, Jaeden Noel", "Plot": "A reluctant babysitter must protect three kids from an invasion of ravenous critters.", "Language": "English", "Country": "USA", "Awards": "N/A",
     "Poster": "https://m.media-amazon.com/images/M/MV5BYzIzYTY0N2UtNDI5Ni00OTM4LTkyMTUtMDQ1ODJiMTg2MDRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg", "Ratings": [{"Source": "Internet Movie Database", "Value": "3.7/10"}, {"Source": "Rotten Tomatoes", "Value": "44%"}], "Metascore": "N/A", "imdbRating": "3.7", "imdbVotes": "2,161", "imdbID": "tt10240612", "Type": "movie", "DVD": "23 Jul 2019", "BoxOffice": "N/A", "Production": "Blue Ribbon Content", "Website": "N/A", "Response": "True"},
    {"Title": "Dungeons & Dragons: Wrath of the Dragon God", "Year": "2005", "Rated": "Not Rated", "Released": "01 Sep 2005", "Runtime": "105 min", "Genre": "Action, Adventure, Fantasy", "Director": "Gerry Lively", "Writer": "Robert Kimmel, Gerry Lively, Brian Rudnick", "Actors": "Bruce Payne, Mark Dymond, Clemency Burton-Hill, Ellie Chidzey", "Plot": "Together, four heroes build their own army to retrieve the orb, using elemental forces to defeat Damodar before he summons the sleeping black dragon.",
     "Language": "English", "Country": "Germany, UK, USA", "Awards": "N/A", "Poster": "https://m.media-amazon.com/images/M/MV5BMTUzNzg2OTI2Nl5BMl5BanBnXkFtZTgwNzQzODkwMzE@._V1_SX300.jpg", "Ratings": [{"Source": "Internet Movie Database", "Value": "4.7/10"}, {"Source": "Rotten Tomatoes", "Value": "29%"}], "Metascore": "N/A", "imdbRating": "4.7", "imdbVotes": "5,606", "imdbID": "tt0406728", "Type": "movie", "DVD": "06 May 2008", "BoxOffice": "N/A", "Production": "New Line Cinema", "Website": "N/A", "Response": "True"},
    {"Title": "House of the Dead", "Year": "2003", "Rated": "R", "Released": "10 Oct 2003", "Runtime": "90 min", "Genre": "Action, Adventure, Horror", "Director": "Uwe Boll", "Writer": "Mark A. Altman (story), Dan Bates (story), Dave Parker (screenplay), Mark A. Altman (screenplay)", "Actors": "Jonathan Cherry, Tyron Leitso, Clint Howard, Ona Grauer", "Plot": "A group of college students travels to a mysterious island to attend a rave, which is soon taken over by bloodthirsty zombies.", "Language": "English", "Country": "Germany, Canada, USA", "Awards": "2 wins.", "Poster": "https://m.media-amazon.com/images/M/MV5BNzlmNTFlN2QtM2IxZi00NDc0LTgyMTQtNDNjNTBmODQzZDVjXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg", "Ratings": [
        {"Source": "Internet Movie Database", "Value": "2.0/10"}, {"Source": "Rotten Tomatoes", "Value": "3%"}, {"Source": "Metacritic", "Value": "15/100"}], "Metascore": "15", "imdbRating": "2.0", "imdbVotes": "36,067", "imdbID": "tt0317676", "Type": "movie", "DVD": "06 Sep 2016", "BoxOffice": "$10,249,719", "Production": "Mindfire Entertainment", "Website": "N/A", "Response": "True"},
    {"Title": "The Blackout", "Year": "2009", "Rated": "N/A", "Released": "30 Sep 2012", "Runtime": "80 min", "Genre": "Horror, Sci-Fi, Thriller", "Director": "Robert David Sanders", "Writer": "Jim Beck (screenplay)", "Actors": "Barbara Streifel Sanders, Joseph Dunn, Ian Malcolm, Michael Caruso", "Plot": "It's Christmas Eve, the city goes dark, and the few remaining tenants of The Ravenwood find themselves trapped in their building. And they are not alone.", "Language": "English", "Country": "USA", "Awards": "N/A", "Poster": "https://m.media-amazon.com/images/M/MV5BMjg3NzQ1YWItZDY4Ny00OTVhLWI4MTAtOGI1NTNjZTFjMWExXkEyXkFqcGdeQXVyNzMzMjU5NDY@._V1_SX300.jpg", "Ratings": [
        {"Source": "Internet Movie Database", "Value": "3.3/10"}, {"Source": "Rotten Tomatoes", "Value": "0%"}], "Metascore": "N/A", "imdbRating": "3.3", "imdbVotes": "1,617", "imdbID": "tt1489946", "Type": "movie", "DVD": "N/A", "BoxOffice": "N/A", "Production": "N/A", "Website": "N/A", "Response": "True"},
    {"Title": "Piranha 3DD", "Year": "2012", "Rated": "R", "Released": "14 Jul 2012", "Runtime": "83 min", "Genre": "Comedy, Horror", "Director": "John Gulager", "Writer": "Patrick Melton, Marcus Dunstan, Joel Soisson, Pete Goldfinger (characters), Josh Stolberg (characters)", "Actors": "Danielle Panabaker, Matt Bush, Katrina Bowden, Jean-Luc Bilodeau", "Plot": "After the events at Lake Victoria, the pre-historic school of blood-thirsty piranhas make their way into a newly opened waterpark.", "Language": "English", "Country": "USA, Japan", "Awards": "2 wins & 5 nominations.", "Poster": "https://m.media-amazon.com/images/M/MV5BMjAzMzY4NTk0M15BMl5BanBnXkFtZTcwMDA4ODU3Nw@@._V1_SX300.jpg", "Ratings": [
        {"Source": "Internet Movie Database", "Value": "3.7/10"}, {"Source": "Rotten Tomatoes", "Value": "13%"}, {"Source": "Metacritic", "Value": "24/100"}], "Metascore": "24", "imdbRating": "3.7", "imdbVotes": "40,462", "imdbID": "tt1714203", "Type": "movie", "DVD": "10 Aug 2016", "BoxOffice": "$376,512", "Production": "Mark Canton, IPW", "Website": "N/A", "Response": "True"},
    {"Title": "The Mist", "Year": "2017", "Rated": "TV-14", "Released": "22 Jun 2017", "Runtime": "42 min", "Genre": "Drama, Horror, Sci-Fi", "Director": "N/A", "Writer": "Christian Torpe", "Actors": "Morgan Spector, Alyssa Sutherland, Gus Birney, Danica Curcic", "Plot": "After an eerie mist rolls into a small town, the residents must battle the mysterious mist and its threats, fighting to maintain their morality and sanity.",
     "Language": "English", "Country": "Canada, USA", "Awards": "2 nominations.", "Poster": "https://m.media-amazon.com/images/M/MV5BMzE3MDk0ODkwM15BMl5BanBnXkFtZTgwMzA5NTk5MTI@._V1_SX300.jpg", "Ratings": [{"Source": "Internet Movie Database", "Value": "5.4/10"}], "Metascore": "N/A", "imdbRating": "5.4", "imdbVotes": "22,638", "imdbID": "tt5639976", "Type": "series", "totalSeasons": "1", "Response": "True"},
    {"Title": "A Quiet Place", "Year": "2018", "Rated": "PG-13", "Released": "06 Apr 2018", "Runtime": "90 min", "Genre": "Drama, Horror, Sci-Fi", "Director": "John Krasinski", "Writer": "Bryan Woods (screenplay by), Scott Beck (screenplay by), John Krasinski (screenplay by), Bryan Woods (story by), Scott Beck (story by)", "Actors": "Emily Blunt, John Krasinski, Millicent Simmonds, Noah Jupe", "Plot": "In a post-apocalyptic world, a family is forced to live in silence while hiding from monsters with ultra-sensitive hearing.", "Language": "American Sign Language, English", "Country": "USA",
     "Awards": "Nominated for 1 Oscar. Another 34 wins & 113 nominations.", "Poster": "https://m.media-amazon.com/images/M/MV5BMjI0MDMzNTQ0M15BMl5BanBnXkFtZTgwMTM5NzM3NDM@._V1_SX300.jpg", "Ratings": [{"Source": "Internet Movie Database", "Value": "7.5/10"}, {"Source": "Rotten Tomatoes", "Value": "96%"}, {"Source": "Metacritic", "Value": "82/100"}], "Metascore": "82", "imdbRating": "7.5", "imdbVotes": "417,009", "imdbID": "tt6644200", "Type": "movie", "DVD": "26 Jun 2018", "BoxOffice": "$188,024,361", "Production": "Sunday Night, Platinum Dunes", "Website": "N/A", "Response": "True"},
    {"Title": "Monsters, Inc.", "Year": "2001", "Rated": "G", "Released": "02 Nov 2001", "Runtime": "92 min", "Genre": "Animation, Adventure, Comedy, Family, Fantasy", "Director": "Pete Docter, David Silverman(co-director), Lee Unkrich(co-director)", "Writer": "Pete Docter (original story by), Jill Culton (original story by), Jeff Pidgeon (original story by), Ralph Eggleston (original story by), Andrew Stanton (screenplay by), Daniel Gerson (screenplay by)", "Actors": "John Goodman, Billy Crystal, Mary Gibbs, Steve Buscemi", "Plot": "In order to power the city, monsters have to scare children so that they scream. However, the children are toxic to the monsters, and after a child gets through, two monsters realize things may not be what they think.",
     "Language": "English", "Country": "USA", "Awards": "Won 1 Oscar. Another 14 wins & 38 nominations.", "Poster": "https://m.media-amazon.com/images/M/MV5BMTY1NTI0ODUyOF5BMl5BanBnXkFtZTgwNTEyNjQ0MDE@._V1_SX300.jpg", "Ratings": [{"Source": "Internet Movie Database", "Value": "8.1/10"}, {"Source": "Rotten Tomatoes", "Value": "96%"}, {"Source": "Metacritic", "Value": "79/100"}], "Metascore": "79", "imdbRating": "8.1", "imdbVotes": "827,162", "imdbID": "tt0198781", "Type": "movie", "DVD": "20 Oct 2013", "BoxOffice": "$290,642,256", "Production": "Walt Disney Productions, Pixar Animation Studios", "Website": "N/A", "Response": "True"},
    {"Title": "The Fly", "Year": "1986", "Rated": "R", "Released": "15 Aug 1986", "Runtime": "96 min", "Genre": "Drama, Horror, Sci-Fi", "Director": "David Cronenberg", "Writer": "George Langelaan (short story), Charles Edward Pogue (screenplay), David Cronenberg (screenplay)", "Actors": "Jeff Goldblum, Geena Davis, John Getz, Joy Boushel", "Plot": "A brilliant but eccentric scientist begins to transform into a giant man/fly hybrid after one of his experiments goes horribly wrong.", "Language": "English", "Country": "USA, UK, Canada", "Awards": "Won 1 Oscar. Another 6 wins & 10 nominations.", "Poster": "https://m.media-amazon.com/images/M/MV5BODcxMGMwOGEtMDUxMi00MzE5LTg4YTYtYjk1YjA4MzQxNTNlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg", "Ratings": [
        {"Source": "Internet Movie Database", "Value": "7.6/10"}, {"Source": "Rotten Tomatoes", "Value": "92%"}, {"Source": "Metacritic", "Value": "79/100"}], "Metascore": "79", "imdbRating": "7.6", "imdbVotes": "163,112", "imdbID": "tt0091064", "Type": "movie", "DVD": "25 Nov 2015", "BoxOffice": "$40,456,565", "Production": "SLM Production Group", "Website": "N/A", "Response": "True"},
    {"Title": "Colossal", "Year": "2016", "Rated": "R", "Released": "21 Apr 2017", "Runtime": "109 min", "Genre": "Comedy, Drama, Fantasy, Sci-Fi", "Director": "Nacho Vigalondo", "Writer": "Nacho Vigalondo", "Actors": "Anne Hathaway, Jason Sudeikis, Austin Stowell, Tim Blake Nelson", "Plot": "Gloria is an out-of-work party girl forced to leave her life in New York City and move back home. When reports surface that a giant creature is destroying Seoul, she gradually comes to the realization that she is somehow connected to this phenomenon.", "Language": "English, Korean",
     "Country": "Canada, USA, Spain, South Korea", "Awards": "3 wins & 8 nominations.", "Poster": "https://m.media-amazon.com/images/M/MV5BMTY2NTExOTA2MF5BMl5BanBnXkFtZTgwNTMwMjE2MTI@._V1_SX300.jpg", "Ratings": [{"Source": "Internet Movie Database", "Value": "6.2/10"}, {"Source": "Rotten Tomatoes", "Value": "81%"}, {"Source": "Metacritic", "Value": "70/100"}], "Metascore": "70", "imdbRating": "6.2", "imdbVotes": "60,308", "imdbID": "tt4680182", "Type": "movie", "DVD": "10 Jul 2017", "BoxOffice": "$3,029,287", "Production": "Brightlight Pictures", "Website": "N/A", "Response": "True"},
    {"Title": "Rampage", "Year": "2018", "Rated": "PG-13", "Released": "13 Apr 2018", "Runtime": "107 min", "Genre": "Action, Adventure, Sci-Fi", "Director": "Brad Peyton", "Writer": "Ryan Engle (screenplay by), Carlton Cuse (screenplay by), Ryan J. Condal (screenplay by), Adam Sztykiel (screenplay by), Ryan Engle (story by)", "Actors": "Dwayne Johnson, Naomie Harris, Malin Akerman, Jeffrey Dean Morgan", "Plot": "When three different animals become infected with a dangerous pathogen, a primatologist and a geneticist team up to stop them from destroying Chicago.", "Language": "English, American Sign Language",
     "Country": "USA", "Awards": "7 nominations.", "Poster": "https://m.media-amazon.com/images/M/MV5BNDA1NjA3ODU3OV5BMl5BanBnXkFtZTgwOTg3MTIwNTM@._V1_SX300.jpg", "Ratings": [{"Source": "Internet Movie Database", "Value": "6.1/10"}, {"Source": "Rotten Tomatoes", "Value": "51%"}, {"Source": "Metacritic", "Value": "45/100"}], "Metascore": "45", "imdbRating": "6.1", "imdbVotes": "148,362", "imdbID": "tt2231461", "Type": "movie", "DVD": "26 Jun 2018", "BoxOffice": "$101,028,233", "Production": "Wrigley Pictures, Seven Bucks Productions", "Website": "N/A", "Response": "True"},
    {"Title": "Tremors", "Year": "1990", "Rated": "PG-13", "Released": "19 Jan 1990", "Runtime": "96 min", "Genre": "Comedy, Horror", "Director": "Ron Underwood", "Writer": "S.S. Wilson (story), Brent Maddock (story), Ron Underwood (story), S.S. Wilson (screenplay), Brent Maddock (screenplay)", "Actors": "Kevin Bacon, Fred Ward, Finn Carter, Michael Gross", "Plot": "Natives of a small isolated town defend themselves against strange underground creatures which are killing them one by one.", "Language": "English", "Country": "USA", "Awards": "5 nominations.", "Poster": "https://m.media-amazon.com/images/M/MV5BMTEzNjkwMzIyMjZeQTJeQWpwZ15BbWU4MDI2NTU5ODYx._V1_SX300.jpg", "Ratings": [
        {"Source": "Internet Movie Database", "Value": "7.1/10"}, {"Source": "Rotten Tomatoes", "Value": "86%"}, {"Source": "Metacritic", "Value": "65/100"}], "Metascore": "65", "imdbRating": "7.1", "imdbVotes": "122,737", "imdbID": "tt0100814", "Type": "movie", "DVD": "03 Oct 2015", "BoxOffice": "$16,667,084", "Production": "Universal Pictures", "Website": "N/A", "Response": "True"},
    {"Title": "Night of the Lepus", "Year": "1972", "Rated": "PG", "Released": "04 Oct 1972", "Runtime": "88 min", "Genre": "Horror, Sci-Fi, Thriller", "Director": "William F. Claxton", "Writer": "Don Holliday (screenplay), Gene R. Kearney (screenplay), Russell Braddon (novel)", "Actors": "Stuart Whitman, Janet Leigh, Rory Calhoun, DeForest Kelley", "Plot": "Giant mutant rabbits terrorize the south-west.", "Language": "English", "Country": "USA", "Awards": "N/A", "Poster": "https://m.media-amazon.com/images/M/MV5BMjM5NTk3N2EtNGZkMy00NTdhLWE0NGQtZDhkNzA4NjJjNWNiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg", "Ratings": [
        {"Source": "Internet Movie Database", "Value": "4.2/10"}, {"Source": "Rotten Tomatoes", "Value": "8%"}, {"Source": "Metacritic", "Value": "37/100"}], "Metascore": "37", "imdbRating": "4.2", "imdbVotes": "4,543", "imdbID": "tt0069005", "Type": "movie", "DVD": "22 Mar 2013", "BoxOffice": "N/A", "Production": "A.C. Lyles Productions", "Website": "N/A", "Response": "True"},
    {"Title": "Swamp Thing", "Year": "1982", "Rated": "PG", "Released": "19 Feb 1982", "Runtime": "91 min", "Genre": "Horror, Sci-Fi", "Director": "Wes Craven", "Writer": "Wes Craven", "Actors": "Louis Jourdan, Adrienne Barbeau, Ray Wise, David Hess", "Plot": "After a violent incident with a special chemical, a research scientist is turned into a swamp plant monster.", "Language": "English", "Country": "USA", "Awards": "1 nomination.",
     "Poster": "https://m.media-amazon.com/images/M/MV5BYWNjMTZiM2YtMDkwOS00ZmJhLThmNzItZjFhMjEyZDliM2Y5XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg", "Ratings": [{"Source": "Internet Movie Database", "Value": "5.4/10"}, {"Source": "Rotten Tomatoes", "Value": "63%"}, {"Source": "Metacritic", "Value": "50/100"}], "Metascore": "50", "imdbRating": "5.4", "imdbVotes": "13,205", "imdbID": "tt0084745", "Type": "movie", "DVD": "04 Feb 2014", "BoxOffice": "N/A", "Production": "Swampfilms", "Website": "N/A", "Response": "True"},
    {"Title": "The Mask", "Year": "2017", "Rated": "N/A", "Released": "17 Oct 2017", "Runtime": "139 min", "Genre": "Crime, Fantasy, Thriller", "Director": "Jason Gerbay", "Writer": "Jason Gerbay", "Actors": "Jamie Summers, Cody Anderson, Annie Landkammer, J.G. Busse", "Plot": "After the events of the the first movie, Stanley Ipkiss has a daughter. The daughter finds the mask in Stanley's room and starts wearing it! It is so spooky and scary that the police try to...",
     "Language": "English", "Country": "USA", "Awards": "N/A", "Poster": "https://m.media-amazon.com/images/M/MV5BMWY5MjM3MmQtNmMzNi00ODc1LTg1YjAtMTgyYjRkZGNlOTk3XkEyXkFqcGdeQXVyMTQ0MzMwNQ@@._V1_SX300.jpg", "Ratings": [{"Source": "Internet Movie Database", "Value": "5.3/10"}], "Metascore": "N/A", "imdbRating": "5.3", "imdbVotes": "65", "imdbID": "tt7504864", "Type": "movie", "DVD": "N/A", "BoxOffice": "N/A", "Production": "N/A", "Website": "N/A", "Response": "True"},
    {"Title": "Pokémon Detective Pikachu", "Year": "2019", "Rated": "PG", "Released": "10 May 2019", "Runtime": "104 min", "Genre": "Action, Adventure, Comedy, Family, Mystery, Sci-Fi", "Director": "Rob Letterman", "Writer": "Dan Hernandez (screenplay by), Benji Samit (screenplay by), Rob Letterman (screenplay by), Derek Connolly (screenplay by), Dan Hernandez (story by), Benji Samit (story by), Nicole Perlman (story by), Satoshi Tajiri (based on \"Pokémon\" created by), Ken Sugimori (based on \"Pokémon\" created by), Junichi Masuda (based on \"Pokémon\" created by), Hiroyuki Jinnai (original creator: Detective Pikachu)", "Actors": "Ryan Reynolds, Justice Smith, Kathryn Newton, Bill Nighy",
     "Plot": "In a world where people collect Pokémon to do battle, a boy comes across an intelligent talking Pikachu who seeks to be a detective.", "Language": "English, Japanese", "Country": "USA, Japan, UK, Canada", "Awards": "10 nominations.", "Poster": "https://m.media-amazon.com/images/M/MV5BNDU4Mzc3NzE5NV5BMl5BanBnXkFtZTgwMzE1NzI1NzM@._V1_SX300.jpg", "Ratings": [{"Source": "Internet Movie Database", "Value": "6.6/10"}, {"Source": "Rotten Tomatoes", "Value": "67%"}, {"Source": "Metacritic", "Value": "53/100"}], "Metascore": "53", "imdbRating": "6.6", "imdbVotes": "143,195", "imdbID": "tt5884052", "Type": "movie", "DVD": "23 Jul 2019", "BoxOffice": "$144,105,346", "Production": "Toho Company Ltd., Legendary Pictures", "Website": "N/A", "Response": "True"},
    {"Title": "The Toxic Avenger", "Year": "1984", "Rated": "R", "Released": "11 Apr 1986", "Runtime": "82 min", "Genre": "Action, Comedy, Horror, Sci-Fi", "Director": "Michael Herz, Lloyd Kaufman", "Writer": "Lloyd Kaufman (story), Joe Ritter (screenplay), Lloyd Kaufman (additional material), Gay Partington Terry (additional material), Stuart Strutin (additional material)", "Actors": "Andree Maranda, Mitch Cohen, Jennifer Babtist, Cindy Manion", "Plot": "Tromaville has a monstrous new hero. The Toxic Avenger is born when meek mop boy Melvin falls into a vat of toxic waste. Now evildoers will have a lot to lose.",
     "Language": "English", "Country": "USA", "Awards": "1 nomination.", "Poster": "https://m.media-amazon.com/images/M/MV5BNzViNmQ5MTYtMmI4Yy00N2Y2LTg4NWUtYWU3MThkMTVjNjk3XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg", "Ratings": [{"Source": "Internet Movie Database", "Value": "6.3/10"}, {"Source": "Rotten Tomatoes", "Value": "70%"}, {"Source": "Metacritic", "Value": "42/100"}], "Metascore": "42", "imdbRating": "6.3", "imdbVotes": "25,440", "imdbID": "tt0090190", "Type": "movie", "DVD": "17 Jan 2017", "BoxOffice": "N/A", "Production": "Troma Entertainment Inc.", "Website": "N/A", "Response": "True"}
]

def cleaning_db():
    clean_db = {}
    for el in movie_db:
        new_data = {}
        new_data["Title"] = el["Title"]
        new_data["Poster"] = el["Poster"]
        new_data["Director"] = el["Director"]
        new_data["Year"] = el["Year"]
        new_data["imdbRating"] = el["imdbRating"]
        new_data["Plot"] = el["Plot"]
        new_data["Actors"] = el["Actors"]
        clean_db[el['imdbID']] = new_data
    return (clean_db)




